await import("./licenseManager.test.mjs");
await import("./urlSecurity.test.mjs");
await import("./statefulProductionGuard.test.mjs");
await import("./mcpHttpAuth.test.mjs");
await import("./mcpScopeEnforcement.test.mjs");
await import("./toolHardening.test.mjs");
await import("./toolRegistry.test.mjs");
await import("./themeFilesBatch.test.mjs");
await import("./themePlanning.test.mjs");
await import("./runtimeExecutionBehavior.test.mjs");
await import("./tenantIsolation.test.mjs");
await import("./tenantIsolationAllTools.test.mjs");
await import("./draftThemeArtifact.test.mjs");
console.log("All hazify tests passed");
