await import("./licenseManager.test.mjs");
await import("./urlSecurity.test.mjs");
await import("./sectionWorkflowArtifacts.test.mjs");
await import("./sectionWorkflowAdapters.test.mjs");
await import("./sectionProviderBridges.test.mjs");
await import("./sectionWorkflowStages.test.mjs");
await import("./replicateSectionCompat.test.mjs");
await import("./mcpHttpAuth.test.mjs");
await import("./toolHardening.test.mjs");
console.log("All hazify tests passed");
